name: Deploy Next.js to VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # Or your desired Node.js version

      - name: Install Dependencies
        run: npm install

      - name: Build Application
        run: |
          for secret in $(env); do
            echo "Writing environment variable $secret"
            echo "$secret=${!secret}" >> .env.production
          done
          # Add other environment variables here
          npm run build

      - name: Deploy to VM
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          source: '.next, package.json, public, next.config.js'
          target: '~/events-planner' # A directory on your VM

      - name: Restart PM2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ~/stefan-events
            npm install --production
            pm2 restart stefan-events
