name: Deploy Next.js to VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # Or your desired Node.js version

      - name: Install Dependencies
        run: npm install

      - name: Build Application
        run: |
          touch .env.production
            echo "AUTH_GOOGLE_ID=${{ secrets.AUTH_GOOGLE_ID }}" >> .env.production
            echo "AUTH_GOOGLE_SECRET=${{ secrets.AUTH_GOOGLE_SECRET }}" >> .env.production
            echo "AUTH_SECRET=${{ secrets.AUTH_SECRET }}" >> .env.production
            echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> .env.production
            echo "DATABASE_URL_POOLED=${{ secrets.DATABASE_URL_POOLED }}" >> .env.production
            echo "DB_HOST=${{ secrets.DB_HOST }}" >> .env.production
            echo "DB_PORT=${{ secrets.DB_PORT }}" >> .env.production
            echo "AUTH_URL=${{ secrets.AUTH_URL }}" >> .env.production
            echo "POSTGRES_DB=${{ secrets.POSTGRES_DB }}" >> .env.production
            echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" >> .env.production
            echo "POSTGRES_USER=${{ secrets.POSTGRES_USER }}" >> .env.production
          # Add other environment variables here
          npm run build

      - name: Deploy to VM
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          source: '.next, package.json, public, next.config.js'
          target: '~/events-planner' # A directory on your VM

      - name: Restart PM2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ~/events-planner
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh
            npm install --production
            pm2 restart stefan-events
